### ISSUE TITLE
code review1

### ISSUE THREAD

**Issue by stephenLYZ** [Elegenthus/IFE-task-5#1]
- 图片路径问题，因为你使用的是相对路径，所以正确引用图片是使用'/',比如你写的是这样：‘src="\images\baidu.png"’，正确是这样：'src="images/baidu.png'或这样 ‘ src="./images/baidu.png"’,这里值得注意的两个方面是相对路径使用'/',还有前面用一个点或者不用表示当前根目录，用两个点表示上级目录，这样说应该够详细了吧，还不懂的话，就面向谷歌吧
- css reset。如果你观察够仔细的话，你会发现你网页的内容离窗口边缘会有一部分空白，你审查元素也会发现body有一部分多出来的margin，这是怎么回事呢？你可以谷歌一下css reset的内容以及为什么要用css reset。
- 下方出现滚动条。我看了一下你的源码，具体原因是因为你宽度设置100%的情况下又设置了margin-left为50%，还有一些小的原因你自己再检查一下。
  右侧表单问题。既然是一个表单，你应该用一个form标签把他们包裹起来。以及不能拿p标签用来换行。
- 行内样式。在一般情况下既然引入了css文件，那就最好避免使用行内样式，做到内容与样式分离。
  编码规范问题。写代码要写就要认真写，就像你写文章，保证卷面整洁、格式对齐、名称易懂是十分必要的，你写的代码也是如此，多余空格不要、代码对齐、命名语义化，不要什么abcdefg，这样会有点小学生的赶脚。

**Comment by Elegenthus** [comment]
问题已修改：）
